"""Static seed articles used as fallback when RSS feeds are unreachable."""

SEED_ARTICLES = [
    {
        "title": "OpenAI Launches GPT-5 with Breakthrough Reasoning Capabilities",
        "url": "https://techcrunch.com/ai/openai-gpt5-launch",
        "summary": "OpenAI's latest model demonstrates significant leaps in multi-step reasoning, mathematics, and code generation — passing the bar exam in the 90th percentile.",
        "published": "Mon, 02 Jun 2026 08:00:00 +0000",
        "source": "TechCrunch AI",
    },
    {
        "title": "Anthropic's Claude 4 Sets New Benchmark on Long-Context Understanding",
        "url": "https://venturebeat.com/ai/anthropic-claude-4-benchmark",
        "summary": "Anthropic's Claude 4 model achieves state-of-the-art results on MMLU and HumanEval, with a 1M-token context window enabling entire codebases to be analyzed at once.",
        "published": "Sun, 01 Jun 2026 10:30:00 +0000",
        "source": "VentureBeat AI",
    },
    {
        "title": "Google DeepMind Releases Gemini Ultra 2 for Enterprise Customers",
        "url": "https://www.theverge.com/ai/google-gemini-ultra-2",
        "summary": "Gemini Ultra 2 brings native multimodal reasoning across text, images, video, and audio in a single unified model, now available via Google Cloud.",
        "published": "Sat, 31 May 2026 14:00:00 +0000",
        "source": "The Verge AI",
    },
    {
        "title": "GitHub Copilot Now Generates Full Pull Requests Autonomously",
        "url": "https://www.technologyreview.com/github-copilot-agentic",
        "summary": "Microsoft's GitHub Copilot has evolved into a fully agentic coding assistant, capable of cloning repos, writing code, running tests, and submitting PRs with minimal human input.",
        "published": "Fri, 30 May 2026 09:15:00 +0000",
        "source": "MIT Technology Review",
    },
    {
        "title": "Midjourney v7 Introduces Consistent Characters Across Scenes",
        "url": "https://www.wired.com/ai/midjourney-v7-characters",
        "summary": "Midjourney's new model can maintain consistent character appearances across multiple generated images, a breakthrough for animation studios and game developers.",
        "published": "Thu, 29 May 2026 11:45:00 +0000",
        "source": "Wired AI",
    },
    {
        "title": "Perplexity AI Hits 50 Million Monthly Active Users",
        "url": "https://feeds.arstechnica.com/perplexity-50m-users",
        "summary": "Perplexity's AI-native search engine has reached 50M MAU, driven by its ability to cite sources, answer follow-ups, and integrate with enterprise knowledge bases.",
        "published": "Wed, 28 May 2026 16:00:00 +0000",
        "source": "Ars Technica",
    },
    {
        "title": "The EU AI Act Enters Full Enforcement — What It Means for Developers",
        "url": "https://techcrunch.com/ai/eu-ai-act-enforcement",
        "summary": "With the EU AI Act now in full force, developers of high-risk AI systems must document training data, implement human oversight, and register with national authorities.",
        "published": "Tue, 27 May 2026 08:30:00 +0000",
        "source": "TechCrunch AI",
    },
    {
        "title": "Meta Releases Llama 4 Under Open License, Shaking the AI Market",
        "url": "https://venturebeat.com/ai/meta-llama-4-open",
        "summary": "Meta's Llama 4 series includes models up to 400B parameters, released under a commercial-friendly license that lets companies fine-tune without royalties.",
        "published": "Mon, 26 May 2026 12:00:00 +0000",
        "source": "VentureBeat AI",
    },
    {
        "title": "AI Agents Are Taking Over Software Development Workflows",
        "url": "https://www.technologyreview.com/ai-agents-software-dev",
        "summary": "A new wave of autonomous AI agents can handle entire development sprints: from requirements to deployment, with engineers shifting into reviewer roles.",
        "published": "Sun, 25 May 2026 09:00:00 +0000",
        "source": "MIT Technology Review",
    },
    {
        "title": "Apple Intelligence Gains On-Device LLM With Private Cloud Compute",
        "url": "https://www.theverge.com/ai/apple-intelligence-llm",
        "summary": "Apple's latest AI update routes sensitive queries to on-device models and only escalates to its Private Cloud Compute for complex tasks — without exposing data to Apple.",
        "published": "Sat, 24 May 2026 15:30:00 +0000",
        "source": "The Verge AI",
    },
    {
        "title": "Researchers Achieve 1000x Speedup in AI Inference via New Architecture",
        "url": "https://www.wired.com/ai/inference-speedup-architecture",
        "summary": "A Stanford and MIT collaboration introduces Sparse Mixture-of-Experts routing that activates only 0.1% of parameters per token, dramatically cutting inference cost.",
        "published": "Fri, 23 May 2026 10:00:00 +0000",
        "source": "Wired AI",
    },
    {
        "title": "AI-Powered Drug Discovery Cuts Clinical Trial Time by 40%",
        "url": "https://feeds.arstechnica.com/ai-drug-discovery-trials",
        "summary": "Pharmaceutical companies using AI-driven molecule screening and trial design have reduced average drug development timelines from 12 years to under 7.",
        "published": "Thu, 22 May 2026 13:00:00 +0000",
        "source": "Ars Technica",
    },
    {
        "title": "OpenAI's Operator Agent Can Now Shop, Book Travel, and File Taxes",
        "url": "https://techcrunch.com/ai/openai-operator-expanded",
        "summary": "OpenAI expanded its Operator agentic system with new capabilities: it can navigate websites, fill forms, verify identity, and complete multi-step transactions autonomously.",
        "published": "Wed, 21 May 2026 11:00:00 +0000",
        "source": "TechCrunch AI",
    },
    {
        "title": "Video Generation AI Can Now Produce Feature-Length Films",
        "url": "https://venturebeat.com/ai/video-generation-feature-film",
        "summary": "Sora and competing video-generation systems have crossed a new threshold: they can now produce coherent, hour-long video narratives with consistent characters and plots.",
        "published": "Tue, 20 May 2026 14:00:00 +0000",
        "source": "VentureBeat AI",
    },
    {
        "title": "Nvidia Announces Blackwell Ultra GPUs — 10x AI Training Throughput",
        "url": "https://www.technologyreview.com/nvidia-blackwell-ultra",
        "summary": "Nvidia's next-generation Blackwell Ultra chips deliver 10 petaflops of AI training compute per GPU, enabling trillion-parameter models to train in days instead of months.",
        "published": "Mon, 19 May 2026 09:30:00 +0000",
        "source": "MIT Technology Review",
    },
    {
        "title": "Microsoft Copilot+ PCs Sell Out as AI PC Wave Hits Mainstream",
        "url": "https://www.theverge.com/ai/microsoft-copilot-pcs-sellout",
        "summary": "AI-native PCs with dedicated neural processing units and on-device LLMs have hit mainstream adoption, with Microsoft's Copilot+ lineup exceeding one million units in the first week.",
        "published": "Sun, 18 May 2026 17:00:00 +0000",
        "source": "The Verge AI",
    },
    {
        "title": "AI Models Are Now Writing 40% of All New Code on GitHub",
        "url": "https://www.wired.com/ai/github-code-ai-percent",
        "summary": "GitHub's annual Octoverse report reveals that AI-generated code now accounts for 40% of all committed code, a jump from 26% the year prior.",
        "published": "Sat, 17 May 2026 12:00:00 +0000",
        "source": "Wired AI",
    },
    {
        "title": "The Hidden Environmental Cost of Training Large Language Models",
        "url": "https://feeds.arstechnica.com/llm-environmental-cost",
        "summary": "A new study reveals that training a frontier LLM emits as much CO2 as 300 transatlantic flights, prompting calls for greener compute infrastructure.",
        "published": "Fri, 16 May 2026 10:30:00 +0000",
        "source": "Ars Technica",
    },
    {
        "title": "Gemini Live Can Now Hold Real-Time Voice Conversations in 50 Languages",
        "url": "https://techcrunch.com/ai/gemini-live-50-languages",
        "summary": "Google's Gemini Live now supports real-time, low-latency voice conversations in 50 languages with near-native fluency, integrating seamlessly with Android and Google Home.",
        "published": "Thu, 15 May 2026 08:00:00 +0000",
        "source": "TechCrunch AI",
    },
    {
        "title": "Anthropic Publishes Safety Blueprint for Agentic AI Systems",
        "url": "https://venturebeat.com/ai/anthropic-safety-blueprint-agentic",
        "summary": "Anthropic's new paper outlines principles for safe autonomous AI agents: minimal footprint, reversible actions, human escalation, and auditable decision trails.",
        "published": "Wed, 14 May 2026 14:00:00 +0000",
        "source": "VentureBeat AI",
    },
]
